---

stages:
  - build
  - build72
  - build73
  - build74

.common:
  image: docker
  services:
    - docker:dind
  retry: 2
  tags:
    - kubernetes
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375
  script:
    - cd ${BASE:?}
    - |
      export DOCKER_TAG=${PHP_VERSION}
      if [ ${BASE} = "centos7" ]; then
        PHP_VERSION=$(echo $DOCKER_TAG | sed -E 's/([0-9]).([0-9])/\1\2/g')
      fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --no-cache --pull --network host --build-arg PHP_VERSION=$PHP_VERSION --tag $CI_REGISTRY_IMAGE:${DOCKER_TAG} --tag $CI_REGISTRY_IMAGE:${DOCKER_TAG}-${CI_COMMIT_SHORT_SHA}  .
  #  - docker push $CI_REGISTRY_IMAGE:${DOCKER_TAG}
  #  - docker push $CI_REGISTRY_IMAGE:${DOCKER_TAG}-${CI_COMMIT_SHORT_SHA}
  when: on_success
  only:
    - master
    - hotfix/maybe-fix-cento8 

#PHP 5.6:
#  stage: build
#  variables:
#    PHP_VERSION: '5.6'
#    BASE: 'centos7'
#  extends: .common

#PHP 7.0:
#  stage: build
#  variables:
#    PHP_VERSION: '7.0'
#    BASE: 'centos7'
#  extends: .common

#PHP 7.1:
#  stage: build
#  variables:
#    PHP_VERSION: '7.1'
#    BASE: 'centos7'
#  extends: .common

PHP 7.2:
  stage: build72
  variables:
    PHP_VERSION: '7.2'
    BASE: 'centos8'
  extends: .common

PHP 7.3:
  stage: build73
  variables:
    PHP_VERSION: '7.3'
    BASE: 'centos8'
  extends: .common

PHP 7.4:
  stage: build74
  variables:
    PHP_VERSION: '7.4'
    BASE: 'centos8'
  extends: .common

