name: ci

on:
  push:
    branches:
      - 'feature/multi-arch'

jobs:
  php56:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=5.6
          tags: 10up/base-php:5.6
  php70:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=7.0
          tags: 10up/base-php:7.0
  php71:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=7.1
          tags: 10up/base-php:7.2
  php72:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=7.2
          tags: 10up/base-php:7.2
  php73:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=7.3
          tags: 10up/base-php:7.3
  php74:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=7.4
          tags: 10up/base-php:7.4
  php80:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=8.0
          tags: 10up/base-php:8.0

